config_version: "1.0.0"

servicenow:
  instance_url: ""
  api_path: "/api/now/table"
  table: "sc_request"
  query_params:
    sysparm_limit: 10
    sysparm_offset: 0
    sysparm_display_value: false
  headers:
    Accept: "application/json"
